### ISSUE TITLE
Probably worth to deprecate in favour of `gulp.util.noop()`

### ISSUE THREAD

**Issue by niksumeiko** [garfieldius/gulp-empty#2]
Gulp has its empty function [`gulp.util.noop()`](https://github.com/gulpjs/gulp-util#noop) that is supposed to do exactly what your module does.

``` js
let util = require('gulp-util');
let uglify = require('gulp-uglify');

gulp.task('js',() => {
    return gulp.src('src/js/*.js')
        .pipe(util.env.production ? uglify() : util.noop())
        .pipe(gulp.dest('dist/js'));
});
```

Probably would be worth to deprecate your module in favour of [Gulp utility functions for gulp plugins](https://github.com/gulpjs/gulp-util) or, at least, point out a reference to it? So people know there's an official option available, bundled with many other useful utils.

Please don't consider my proposal offensive, just wishing to do better for a community&zwnj;_!_
Feel free to close/delete this issue, otherwise.

**Comment by garfieldius** [comment]
Or the gulp-if package. Good point, will do.

**Comment by gkiely** [comment]
@garfieldius is it possible to remove this deprecation, I don't use gulp util and just want to use this package.

Thanks, Grant.

**Comment by garfieldius** [comment]
I have no intention of actually removing the package, it will remain in the registry and the warning is merely a reminder that it is not actively supported. The deprecation, in this context, means that there will be no compatibility fixes for new versions of node or its JS engine, not that it will be removed.
